// Generated by ./collate.pl

var stanzas = {
   "E15" : [
      "Figure E15: EVENTUALLY (1, 1, -1, 1)",
      "Our path now in a new direction lies,",
      "No longer spatial: time-like is our way",
      "Hidden down here from the spinning skies",
      "Millennia are reckoned as a day.",
      "We see a buried future: Earth turned gray",
      "And sere, where humans huddle in their den",
      "Leach from radioactive stones, a stay",
      "Of execution - for the day comes when",
      "Their race at last is run: there'll be no more \"And then...\""
   ],
   "E13" : [
      "Figure E13: YIELD (1, 1, -1, -1)",
      "Through a rude tunnel, north once more we fare",
      "Into a chamber perilous indeed:",
      "Here, deep in Afric stone, a crystal rare,",
      "The yellow francevillite, sees water bleed",
      "And moderate the neutrons' fatal seed",
      "To start a chain-reaction underground",
      "Two billion years before mankind will breed.",
      "The hills of OKLO ferment without sound",
      "Or outward sign, a grim Prometheus yet bound."
   ],
   "B6" : [
      "Figure B6: LIFE (0, 0, 0, 1)",
      "Endless futures branch, redoubling,",
      "But life begins with jugglings so rare,",
      "So subtle that the butterflyâs soft wing",
      "Is as Behemothâs footfall by compare.",
      "You need not fear that other versions share",
      "Your life in an alternate destiny:",
      "Whether this bring joy or black despair,",
      "Of one timeline alone are you made free,",
      "The only UNIVERSE in which you came to be."
   ],
   "E8" : [
      "Figure E8: SOCIETY\r (-1, 1, 1, 1)",
      "Ascending to a chamber high and bright\r",
      "In which a hundred thousand worlds are shown\r",
      "Communing each to each: for in the night\r",
      "That FERMI though so still, exchange has grown,\r",
      "But only by mature species known.\r",
      "So adolescents, socially outgunned,\r",
      "Will in the grandest ballroom feel alone\r",
      "And sit in silence, like a mullet stunned,\r",
      "Or blurt inanities, then wonder why theyâre shunned.\r"
   ],
   "C11" : [
      "Figure C11: HOLLOW (0, 0, -1, -1)",
      "We tread a fungous lawn as the wind dies.",
      "The surface? No, but see a cavern vast,",
      "A world inverse, with continental skies,",
      "But not the shapes we know, for here the past",
      "Of Earth survives: the saurians, the last",
      "Of ancient Mu and of Atlantis proud",
      "Baluchitheria take their high repast",
      "From ginkgo-trees; a twilight without cloud,",
      "Low palaces beneath the starless heavenâs shroud."
   ],
   "C1" : [
      "Figure C1: NEBEL (-1, -1, 0, 0)",
      "Westward from that shore, we see a wall",
      "Frozen but indistinct, as if a cloud",
      "Were still and square: through a ghostly hall",
      "We enter, footsteps muffled by the shroud",
      "Of the strange pavement, for nothing loud",
      "Can enter this blue chamber, builded well,",
      "Each brick is an infinitesimal crowd",
      "Of tiny atomies, an ÃRO-GEL,",
      "A smoke made solid, that no wind can e'er dispel."
   ],
   "C18" : [
      "Figure C18: ACOUSTIC\r (0, 1, 0, 1)",
      "Descend to utter dark, where we can see\r",
      "Nothing but black, yet feel the open air.\r",
      "A future time where fire's energy\r",
      "Has used up all its fuel, but Nature fair\r",
      "Repays the want with SOUND. Now, listen, where\r",
      "The forest murmurs dimly, hear the poise\r",
      "And grace of soaring birds, the music rare\r",
      "That moonlight jingles from the waves its toys,\r",
      "And warm your hands before a brazier of noise.\r"
   ],
   "D13" : [
      "Figure D13: ANOMALOCARIS (0, -1, -1, -1)",
      "Eastward to a warmer, shallow sea,",
      "The womb of Nature: in its sunny brine",
      "Greet multicellular perplexity.",
      "This slug with hackles like a porcupine;",
      "That wormy mass of tentacle and spine;",
      "And, greatest of them all, a swimming PRAWN,",
      "Its mouthparts iris'd open as to dine:",
      "\"Ye latter creatures, look on us and mourn.",
      "For each shape that survived, a thousand more were born.\""
   ],
   "E9" : [
      "Figure E9: FUMAROLE (1, -1, -1, -1)",
      "Long ere upper ocean was alive",
      "Hidden from the light of Earth's first day",
      "Along a ridge volcanic, creatures thrive",
      "Far from Sol's photosynthetic sway.",
      "Mats of microbes feast on boiling clay,",
      "Great tube-worms sport their bloody plumage well,",
      "And here a squamous winkle makes its way",
      "With scaly foot and iron sulphide shell,",
      "A heavy metal snail, a mollusc fit for HELL."
   ],
   "C8" : [
      "Figure C8: SIPHON (0, -1, -1, 0)",
      "To present, now, in a low chamber, moist",
      "And busy, full of engines intertwined",
      "Lever and waterwheel, pulley and joist",
      "Rotate and shift, most cunningly designed.",
      "From smaller cups to larger, so we find",
      "Each trickle turns a larger, slower wheel",
      "The tiniest turn quickest, while the mind",
      "Can barely credit that the largest reel",
      "Is turned by little drops, a Juggernaut of steel."
   ],
   "D24" : [
      "Figure D24: TERRA (1, -1, 0, 1)",
      "Upward now, but not to scorching skies",
      "Futures, by nature manifold, not one",
      "An odour as of clay that bakes and dries",
      "A room of rude ADOBE, where the sun",
      "Filters thro' torn curtains: here has run",
      "A million years of mixture, which has made",
      "All matter jumbled, entropick and dun:",
      "As coloured doughs, when long have children played,",
      "Revert to an unhealthy purple-brownish shade."
   ],
   "C2" : [
      "Figure C2: DECANTER (-1, 0, 0, -1)",
      "Towards the west, a fair pavilion trace:",
      "We enter through an arch of metal bright.",
      "Though row on row of shelving fills the space,",
      "The room withal is glittering and light,",
      "For crystal vessels clear stand left and right,",
      "Each with its epoch labelled with great care:",
      "âORDOVICIAN â CARBONATED â NIGHTâ,",
      "âPERMIAN â HIGH ALPINE â VERY RAREâ,",
      "The archives of the the sky, a library of air."
   ],
   "D21" : [
      "Figure D21: SOUP (1, -1, 0, -1)",
      "Now to another beach, far harsher than",
      "A bow of crystal sand and ocean blue.",
      "The noisome shores of Earth, long before Man:",
      "See in the ruddy clays a rancid stew",
      "Of polymers, stirred and mixed anew,",
      "By steaming tides and radiations scour'd.",
      "See! There! A lipid membrane splits in two,",
      "Precipitates like curd in milk that's sour'd,",
      "And all its rival molecules are soon devour'd."
   ],
   "D18" : [
      "Figure D18: CONTINUUM\r (0, 1, 1, -1)",
      "As we peer still deeper into space\r",
      "The scholar reads a panoply of signs\r",
      "That tell each epoch's story, keeping pace\r",
      "As we descend in darkness in the mines\r",
      "Of ancient photons: see the spectral lines,\r",
      "The LYMAN-ALPHA FOREST - as the light\r",
      "Of young chaotic galaxies combines\r",
      "With neutral hydrogen, and so the bright\r",
      "Mad furnace of the quasar shows a billion years of light.\r"
   ],
   "E7" : [
      "Figure E7: IMMATERIAL\r (-1, 1, -1, 1)",
      "Westward away from this choking stench,\r",
      "We pass into a vast, transparent void,\r",
      "Where minds no longer held in bodiesâ clench\r",
      "Disport within an Earth long since destroyed,\r",
      "Recycled and more gainfully employed\r",
      "As substrate of this ALGEBRAICK SPHERE.\r",
      "Now humankind shall never be annoyed\r",
      "By fleshâs limitations, blind and drear,\r",
      "But go as mystic monads, ever seeing clear.\r"
   ],
   "B1" : [
      "Figure B1: TEMPEST (-1, 0, 0, 0)",
      "South thro' lofty arches we repair",
      "Onto a broad pavillion looking out",
      "From a high prospect: this the realm of Air",
      "Array'd with marble pillars, round about",
      "The zephyr's whisper and the Typhoon's shout",
      "Deafen our hearing - but their are not words",
      "Can tell the vapours, nitrous, rich and stout",
      "Arising from the colony of Birds",
      "Which, nesting here, begrime the marble with their Turds."
   ],
   "E6" : [
      "Figure E6: SUPERMASSIVE (-1, 1, 1, -1)",
      "The second form of light that ever shone,",
      "After a million years of neutral dark,",
      "As matter screamed to show where it had goneâ",
      "Electron stripped from atom, quark from quarkâ",
      "Still visible, red-shifted, clear and stark,",
      "The mighty cauldron of the QUASI-STAR",
      "Yet leaves upon the sky its blazing mark.",
      "Stately elliptical, spiral or bar,",
      "Each galaxy was once a door of Hell ajar."
   ],
   "E2" : [
      "Figure E2: ICES (-1, -1, 1, -1)",
      "Still backward run the clock, until we see",
      "(In inward vision of the heavens past)",
      "A maelstrom of nebulosity",
      "Around the infant Sun. Revolving fast,",
      "The inner circle, subject to the blast",
      "Of newborn light, too hot for ice to form:",
      "Outwards, frosty fragments form the vast",
      "Gas giants: 'twixt them, planetesimals swarm.",
      "The FROST-LINE great from small partitions, cool from warm."
   ],
   "C17" : [
      "Figure C17: EXTREMES\r (0, 1, 1, 0)",
      "From such a distant past, the present seems\r",
      "To dazzle and confuse us. Rocky walls\r",
      "Rough-hewn glow white in horizontal beams\r",
      "Of the low sun, which e'en at twilight spalls\r",
      "Hot ions from the stone on which it falls,\r",
      "Yet at our feet the floor is all of ice.\r",
      "The sunlight sweeps: at intervals, it stalls\r",
      "As MERCURY turns three times, orbits twice,\r",
      "Its polar craters in eternal winter's vise.\r"
   ],
   "D6" : [
      "Figure D6: EMISSION (-1, 0, 1, -1)",
      "Southward, substituting time for space:",
      "Back before the force of gravity",
      "Had kindled fire: darkness on the face",
      "Of all the void, a dim serenity",
      "Of neutral hydrogen, a sunless sea.",
      "But eâen the simplest atom has its song:",
      "Though spin to counter-spin unlikely be",
      "In one, in such great numbers do they throng",
      "We hear the TWENTY-ONE LINE ring out clear and strong."
   ],
   "D15" : [
      "Figure D15: INDOLENS  (0, -1, -1, 1)",
      "Down where nameless horrors wind and slurp,",
      "Dreaming on a dark abyssal plain",
      "Of punishing those apes who dared usurp",
      "Thy brutal, dark and cephalopodic reign-",
      "But humans are no more; so all in vain",
      "Thy long-departed cultists wail'd and leapt.",
      "There are no brains to eat and plunge in pain:",
      "Thy appointment with the stars was left unkept.",
      "Alas, o Elder One, thou hast long overslept."
   ],
   "C12" : [
      "Figure C12: NOCTURNE (0, 0, 1, -1)",
      "Back, further back, we see the Cosmic Void,",
      "The space surrounding and preceding ALL.",
      "With giddiness, our sense of scale destroyed,",
      "What is this garden? Infinitely smallâ",
      "Yet beautiful within its filmy caul,",
      "Cloudy with galaxiesâ with what great pains",
      "We hold our thoughts, lest the bauble fall",
      "And shatter. There our Universe remains,",
      "Safe from disturbance by our overheated brains."
   ],
   "D26" : [
      "Figure D26: TYCHO'S STAR (1, 0, 1, -1)",
      "Ascending now, the Northern heavens view:",
      "In Cassiopeia, a star burns bright,",
      "Unknown to living memory. A new",
      "Addition to the stellar sphere, that might",
      "Admit no change: Elizabethan night",
      "Disfigured by a NOVA. What foretold",
      "The Queen's astrologer? A fearful sight,",
      "Surpassing any alchemist of old,",
      "The carbon of a star transmuted into gold."
   ],
   "D20" : [
      "Figure D20: TELOS\r (0, 1, 1, 1)",
      "From this small fire, to an end of days.\r",
      "If universal growth had been subdued\r",
      "By gravity, to fall back in a blaze,\r",
      "Would time reverse? We see a vision crude,\r",
      "Men rising from their graves and puking food.\r",
      "Yet may such simple fancy run amiss.\r",
      "The GREAT RETURN, our unity renewed,\r",
      "May bring not fiery doom, but synthesis,\r",
      "A richer world. No meagre consolation, this.\r"
   ],
   "C19" : [
      "Figure C19: TRAVERTINE (1, -1, 0, 0)",
      "Toward the south, our vision blocked by steam.",
      "A whiff of sulphur and the sound of drops;",
      "A gust of wind unveils, and, like a dream,",
      "Appears a mighty terrace: from the tops",
      "Of each stepp'd level, trickling water plops",
      "Down to the next, and the droplets bear",
      "DissolvÃ©d lime, insensibly which stops",
      "To build, atom by atom, a rocky stair",
      "Flowing, liquid, stony, lovely beyond compare."
   ],
   "E14" : [
      "Figure E14: IMPACT\r (1, 1, 1, -1)",
      "Quitting Venus, torrid yet serene,\r",
      "We shift once more into the deeper past\r",
      "To gaze upon a cataclysmic scene:\r",
      "Four giant planets, crowded, racing fast\r",
      "About the Sun, till Jupiter has cast\r",
      "His three companions distant from their flock\r",
      "Of planetesimals, which fall to blast\r",
      "The inner planets. Battered by the shock,\r",
      "See Luna's blemishes, a testament to rock.\r"
   ],
   "D14" : [
      "Figure D14: SHORELINE (0, -1, 1, -1)",
      "As Selene her orbit roundabout",
      "Draws now down, now up, the oceans' sides,",
      "So does the Milky Way breathe in and out,",
      "For galaxies, like planets, have their tides,",
      "And on the littoral the Earth abides,",
      "Rich with heavy atoms, in the lee",
      "Where from the super-nova's blast it hides:",
      "In this pool of gas, life came to be,",
      "Along the margins of an interstellar sea."
   ],
   "D8" : [
      "Figure D8: TEMPERATE\r (-1, 0, 1, 1)",
      "We travel south, to a black room so cold\r",
      "Our breath emerges as a freezing fog.\r",
      "The Universe, immeasurably old,\r",
      "Has darkened to that stale, entropick bog\r",
      "That scholars call HEAT DEATH: but as the log\r",
      "Grows slower yet still grows, here life has ways\r",
      "To eke out ancient stars. Timeâs greatest cog\r",
      "Ticks slower still, and creatures of those days\r",
      "Little suspect that we dwelt in the Big Bangâs blaze.\r"
   ],
   "E3" : [
      "Figure E3: AMPHIBIAN (-1, -1, -1, 1)",
      "Take us now far from this tipping point",
      "Into a future, cavernous, dim, with stink",
      "Ammoniack and rank: without joint,",
      "All smooth our round enclosure, nacre-pink,",
      "This is the cockpit: see, the pilots think",
      "And their great living vessel does obey.",
      "The bladder closes round us and we sink",
      "Or rise as it expands: in this far day",
      "Such living submarines will ply their finny way."
   ],
   "D11" : [
      "Figure D11: TONANS\r (-1, 1, 1, 0)",
      "Northward to an onyx-marbled court\r",
      "Whose floor is an enormous ruddy eye.\r",
      "To JUPITER devote, and these his sport:\r",
      "Sulphurous IO, maddened by the fly,\r",
      "EUROPAâS ocean with its icy sky,\r",
      "Remote CALLISTO, beauteous, rejoice\r",
      "In thy Dian: and, borne by eagle high,\r",
      "The handsome GANYMEDE: for Zeusâs choice\r",
      "Is ofttimes like his thunder, in falsetto voice.\r"
   ],
   "D19" : [
      "Figure D19: MÃLANGE\r (0, 1, -1, 1)",
      "Not long that darkened future we disturb\r",
      "But climb a stair down to a furnace-room\r",
      "Whose coal is not of ancient buried herb\r",
      "But refuse of long ages, in the womb\r",
      "Of stone compressed: the midden-heap, the tomb,\r",
      "The factory, the spaceship-yard, the cell.\r",
      "Glowing red and giving off a fume\r",
      "Kaleidoscopic, insolent and fell,\r",
      "As if the sins of Earth were gathered in a smell.\r"
   ],
   "D22" : [
      "Figure D22: TROGLOBITE (1, -1, -1, 0)",
      "Spiraling down a sinkhole ringed with stairs",
      "We descend once more into the ground.",
      "A watery cave we find, with humid airs",
      "Deep in darkness, but even here are found",
      "Strange forms of life: bats that see with sound,",
      "Long-legged bugs that palpitate their way",
      "And in the streams translucent fish abound.",
      "Here the OLM blindly hunts its prey,",
      "Obscene and pallid worm, best hidden from the day."
   ],
   "B7" : [
      "Figure B7: REDOX (0, 1, 0, 0)",
      "A winding stair leads from this solemn scene",
      "Upward to daylight, and a steely gate",
      "All red with rust and twined with tendrils green",
      "Abuzz with life, and creatures, small and great,",
      "Pace their enclosures, pant, and respirate.",
      "So iron, leaf and lung forever burn,",
      "Reduce, combust, exchange and oxidate.",
      "The fire's flame, th'uncoiling of a fern,",
      "In cycles their electrons remit and return."
   ],
   "D7" : [
      "Figure D7: TANGERE\r (-1, 0, -1, 1)",
      "Southward now, material once more,\r",
      "To a great hall, echoing and chill,\r",
      "Nothing is here, it seems, but walls and floor,\r",
      "But through our bodies wild emotions thrill:\r",
      "We love, we hate, we fear, we laugh, until\r",
      "We know that from a world of glass and steel\r",
      "Discarded, human souls these caverns fill,\r",
      "Exiled by their owners from the Real,\r",
      "Bereft of every power save to touch or feel.\r"
   ],
   "D32" : [
      "Figure D32: TEPID\r (1, 1, 0, 1)",
      "A simple fence surrounding ashy meads,\r",
      "And in their midst, a tuffet dark and low\r",
      "Lies steaming in the mud. A notice reads:\r",
      "\"The Earth was not so steadfast long ago,\r",
      "\"When continents could drift and lava flow.\r",
      "\"But age and dryness made the engine stall\r",
      "\"That once made mountains smoke and belch and glow.\r",
      "\"Stranger, you see Earth's last fires fall:\r",
      "\"EXIGUUS, the last volcano of them all.\"\r"
   ],
   "B3" : [
      "Figure B3: STERILE (0, 0, 0, -1)",
      "Here we may not linger â down a stair,",
      "Which halfway turns to up, or so it seems,",
      "Climb to a lonely strand. The briny air",
      "Wakes our drowsy senses, and the gleams",
      "Of breakers dazzle. The ocean teems",
      "With life, but on the land is nothing more",
      "Than arid rock, bleached by the Sunâs beams.",
      "Three milliards of years must pass before",
      "The first brave plants begin to populate the shore."
   ],
   "D10" : [
      "Figure D10: OCTAHEDRON (-1, 1, -1, 0)",
      "Welcome relief for the indignant Nose",
      "In the next dark chamber we have found.",
      "Sulphur a transformation undergoes",
      "Once it has been to lead in crystals bound.",
      "Black and massy, galena, resound",
      "To the slightest Ã¦thereal wave:",
      "Telluric currents thrill deep underground",
      "Guided by cat's-whisker to this cave",
      "So heaviness by light is told, and does behave."
   ],
   "C15" : [
      "Figure C15: APOCALYPSE (0, 1, 0, -1)",
      "By such a narrow pathway leading east",
      "That we perforce must walk in single file",
      "Between steep cliffs of ice. Here was the least",
      "Of generations, winnowed by the trial",
      "Of long volcanic winter. From the isle",
      "Sumatra, covering the planetâs face",
      "With dust and ash, rising many a mile",
      "From TOBA, reaching to the verge of space:",
      "Thy shadow long, that near snuffed out the human race."
   ],
   "A1" : [
      "Figure A1: VIVAMUS (0, 0, 0, 0)",
      "A simple chamber, fresh with morning AIR,",
      "A cheery FIRE burning in its grate.",
      "Of EARTHEN flags the floor, well-swept and bare,",
      "A table set with WATER, food and plate.",
      "Ancient books that all the PAST relate",
      "Or foreshadow the FUTURE yet to come,",
      "Strange instruments to scry the HEAVENSâ state",
      "Or the intestine DEPTHS of matter plumb:",
      "All elements meet here, in equilibrium."
   ],
   "B4" : [
      "Figure B4: FAINT (0, 0, -1, 0)",
      "The truth is at the bottom of a well:",
      "So said the Atomist in ancient days.",
      "Yet here is fungus and an awful smell.",
      "Is this, then, the conclusion of our maze?",
      "Not so, for see the dimly gleaming raysâ",
      "That whet, but do not satiate, our sightâ",
      "And for the last time, upward find our ways",
      "Out of damp, uncomfortable night,",
      "To where, if not an end, at least there will be light."
   ],
   "D28" : [
      "Figure D28: BARYONIC (1, 0, 1, 1)",
      "Kalpa upon Kalpa of cosmic time",
      "Has passed for us: the stars no longer glow,",
      "But orbit through a velvet night sublime,",
      "Cold and in seeming spent. Yet, even so,",
      "As atoms flicker languid to and fro",
      "In aeons they may jump the quantum wall",
      "To fuse and form the isotope we know",
      "as iron, stablest nucleon of all:",
      "Each star in time becomes a mighty CANNON-BALL."
   ],
   "D25" : [
      "Figure D25: AMMONITE (1, 0, -1, -1)",
      "Northward from this gloomy deep, into",
      "A sombre cavern, paved with spiral stones:",
      "\"Once we sail'd in sunny oceans blue,",
      "\"Suspended by our buoyant phragmocones.",
      "\"Now lie we buried deep beneath the bones",
      "\"Of Earth, but shall be raised again to land,",
      "\"As Shaligram of VISHNU that atones;",
      "\"Or those bad serpents which Saint Hilda's hand",
      "\"Will cast and turn to stone on holy Whitby's strand.\""
   ],
   "D16" : [
      "Figure D16: TIRYNS (0, -1, 1, 1)",
      "in a distant future, now we see",
      "Our Milky Way is monstrously deployed",
      "To smash into a neighbour galaxy.",
      "(Though scarcely any star shall be destroyed,",
      "So great the space between, yet much annoyed",
      "By tidal currents, hurtled out at speed",
      "To drift away into the cosmic void.)",
      "Yet what Perseus, on what wingÃ©d steed",
      "Shall save ANDROMEDA in this her hour of need?"
   ],
   "D31" : [
      "Figure D31: RETROGRADE\r (1, 1, 1, 0)",
      "Murmurs the wind as lightly as a dove,\r",
      "We enter a high chamber, well endowed\r",
      "With all the soft accoutrements of love,\r",
      "That looks out on an opalescent cloud.\r",
      "It hides a tortured land beneath its shroud:\r",
      "A barren hell, rotating retroflex.\r",
      "VENUS GENETRIX, beautiful and proud,\r",
      "See science thy mythology perplex\r",
      "And make thine Evening Star a slander on thy sex.\r"
   ],
   "D5" : [
      "Figure D5: TUNNEL (-1, 0, -1, -1)",
      "From pricking ozone glare, toward the south,",
      "We tread a steep defile: a rising howl",
      "Of wind is heard to fret the cavernâs mouth:",
      "A rudely formed and stalactited cowl.",
      "The gale, irregular, as if a foul",
      "And giant creature were by croup annoyed,",
      "Like borborygmus in a Titanâs bowel",
      "As matter settles, breaks, and is destroyed:",
      "The stuttered gale portends that we approach a VOID."
   ],
   "E11" : [
      "Figure E11: TESTUDO (1, -1, -1, 1)",
      "Move we again to far futurity",
      "(Potential, as all such visions are):",
      "Deep below the crust, a sunless sea",
      "Is hidden from the wrath of mother star",
      "As bloated, red, she turns the land to char.",
      "Dark in light only: see, in INFRA-RED,",
      "Deep vents glow bright, the surface black as tar.",
      "Vast Leviathans swim here, filter-fed,",
      "So life within continues though the shell be dead."
   ],
   "E4" : [
      "Figure E4: UNSTABLE (-1, -1, 1, 1)",
      "Around great limbs, a winding stair ascend",
      "Up to a lofty chamber. Here, the fate",
      "Of space itself is pondered; if it tend,",
      "As must all things, unto a lower state",
      "Of energy, the peril may be great.",
      "The very vacuum splintering shall go",
      "From one small seed, dying at the rate",
      "Of light itself: small comfort, for this woe,",
      "That if or when it happen, none can ever know."
   ],
   "C16" : [
      "Figure C16: IGNITION (0, 1, -1, 0)",
      "Obsidian the walls of the next vault",
      "Circled around a single sacred flame",
      "From a jagged crack, a riven fault",
      "Consecrated to Hephaestus lame:",
      "A glossy liquid seeps, which humans name",
      "PETROLEUM. The suns of ancient days,",
      "Absorbed by herb, compressed, transformed: to claim",
      "This prize, the blood of industry, the craze",
      "Of Ares' wrath will spur undending battles' blaze."
   ],
   "C6" : [
      "Figure C6: LIGHTNING (-1, 1, 0, 0)",
      "Brazen the gate to Lightning's airy room",
      "Northwest it faces, son of Air and Fire.",
      "Amber and glass reflect the ruddy gloom",
      "Webbed with divers strands of copper wire.",
      "Sparks leap and crackle skywards in a gyre,",
      "Conducting waves borne upon Aether's wing:",
      "The music of a vast celestial choir.",
      "A million voices mutter, cry and sing,",
      "And our rebellious garments to our members cling."
   ],
   "D9" : [
      "Figure D9: STRIKE (-1, 1, 0, -1)",
      "Northward to a garden, spare and clean,",
      "Where, between raked vortices of sand,",
      "Bare branches, with a smooth and glassy sheen,",
      "But neither twig nor leaf, solemnly stand,",
      "For these trunks are the marks of Zeus' hand",
      "Where lightning-blast has fused the very quartz",
      "To stony columns: wind erodes the land",
      "And leaves behind as FULGURITE the sports",
      "Of ancient thunderclaps' most echoing reports."
   ],
   "C5" : [
      "Figure C5: APPETITE\r (-1, 0, 0, 1)",
      "Ascending now to a great banquet hall\r",
      "We see a table, laden with a feast\r",
      "Delicious in aroma: on each wall\r",
      "Strange epiphytes and congeries of yeast\r",
      "Serve us flesh not robbed from any beast,\r",
      "A stew of trilobites, poached in white wine,\r",
      "And many other species long deceased.\r",
      "Here see art, science, Nature best combine,\r",
      "And, with our end in sight, sit gratefully to dine.\r"
   ],
   "C24" : [
      "Figure C24: EARTHWORKS (1, 1, 0, 0)",
      "Eastward next, into a chamber strange,",
      "Filled with what seems a bulky mass of earth.",
      "Only about its edges may we range,",
      "A musty passage, narrow as a firth.",
      "Its sides bear witness to what gave them birth:",
      "Inverse relief of furniture and walls,",
      "Devoured by termites: beasts of little worth",
      "Consume, digest, transfigure wooden halls:",
      "The daintiest of rooms, for them, but fodder stalls."
   ],
   "C4" : [
      "Figure C4: AIRY\r (-1, 0, 1, 0)",
      "From this chill future to the present day,\r",
      "A tower room of lapis and azure\r",
      "With books and instruments. LE VERRIER\r",
      "And Adams, independently, assure\r",
      "Observers that a world unknown must draw\r",
      "Uranus from its path. And so were France\r",
      "And England set at scientific war.\r",
      "(Yet GALILEO saw it: by mischance,\r",
      "Just at the turning point of its apparent dance.)\r"
   ],
   "D23" : [
      "Figure D23: LONE (1, -1, 1, 0)",
      "A chamber paved with marble and azure",
      "And dedicated to a mystery:",
      "Stubborn as stone, where life will long endure",
      "Or delicate snowflake fragility?",
      "The sole oasis in the nullity",
      "Of endless space? Or does life give birth",
      "In any place where light and water be?",
      "Original enigma, Mother EARTH:",
      "From only one example, hard to judge the worth."
   ],
   "C10" : [
      "Figure C10: GLOBE (0, -1, 0, 1)",
      "By a crude door westward, to a pier",
      "Of rough-hewn coral blocks amid a sea",
      "Calm and shallow, marvellously clear.",
      "Earth in its dotage lacks the energy",
      "To rear up mountains, so the water, free",
      "To grind and weather has worn down the world",
      "To one vast shallows, where, languidly",
      "The heirs of humans bask, gills unfurl'd,",
      "No longer by the tides of earthly passions whirl'd."
   ],
   "C13" : [
      "Figure C13: OBLITERATE (0, 0, -1, 1)",
      "Descending for the last time into Earth",
      "We reach a solemn catacomb of stone",
      "Marked in an unknown script. Of little worth",
      "Our struggle, then, if we must end alone,",
      "Abandoning our citadel of bone.",
      "Yet every person we encountered took",
      "Impressions of us: memories are sown",
      "No less than in a war or learnÃ©d book,",
      "In a confused expression or a dirty look."
   ],
   "C20" : [
      "Figure C20: ASTHENOSPHERE (1, 0, 0, -1)",
      "A hallway grand leads south, all dressed in stone",
      "Of many shades: here is remembered by",
      "Its native rocks, each continental zone",
      "Of ancient time, long hidden from the sky.",
      "Vaalbara's zircon, Doggerland yet dry,",
      "Basalt slabs from Kerguelen afar,",
      "Granite of Farallon, tormented by",
      "Tectonic might, and lost Zealandia's bar,",
      "Beneath the southern waves a home to Neptune's car."
   ],
   "C22" : [
      "Figure C22: ERIDANIA (1, 0, 1, 0)",
      "Now in the present day, in a high room",
      "As cold as ice with walls as red as rust,",
      "With tapestries wove by no earthly loom",
      "Depicting scenes of pageantry and lust,",
      "Carnage and high adventure. But we must",
      "Draw them aside, and fantasy's surcease",
      "We trade for an utopia of dust",
      "On which romance shall not extend its lease:",
      "The planet named for WAR, eternally at peace."
   ],
   "C9" : [
      "Figure C9: ANNALS (0, -1, 1, 0)",
      "Moving to the present, here the floor",
      "Of bland and glossy celadon is made.",
      "GEORGE'S STAR, which Herschel's glass first saw,",
      "Is mirrored in each wall of pallid jade:",
      "URANUS, rolling in its orbit laid",
      "Upon its side, around it swing like toys",
      "Its darkling moons, their master's tilt obeyed.",
      "But all along its path is heard a noise,",
      "The giggling of all the ages' little boys. "
   ],
   "E12" : [
      "Figure E12: WORLD-TREE (1, -1, 1, 1)",
      "Just as the minute polyp, year on year,",
      "Erects beneath the wave a mighty reef,",
      "So, though measured 'gainst the heavens' sphere,",
      "A person or a species' life is brief,",
      "Life obeys, of all commands, the chief,",
      "To multiply: across the spiral wheel",
      "It spreads. For this infection, no relief.",
      "Thus is the fabled YGGDRASIL made real",
      "In countless bio-spheres of adamant and steel."
   ],
   "D2" : [
      "Figure D2: RELEASE (-1, -1, -1, 0)",
      "Downward to a well sunk deep below",
      "The ocean's surface, in a rattling cage",
      "Of iron barsâhere, as white as snow,",
      "In ice is trapped, by pressure and long age,",
      "A treasure and a peril: history's page",
      "May show this methane, product of the sun,",
      "As worthy of our poor descendants' rage",
      "As we may be. Let it not be undone,",
      "A fearful form of feedback, this, the CLATHRATE-GUN."
   ],
   "D3" : [
      "Figure D3: SATURN (-1, -1, 1, 0)",
      "These upper rooms are to celestial spheres",
      "Devoted: present, now, a cork-lined room",
      "Sacred to SATURNUS, long of years.",
      "Pale yellow, nursing Titan's icy womb,",
      "Though lord of death and of the leaden tomb",
      "And that old verse which ancient Latins sing",
      "Yet light enough to float like ocean's spume",
      "(If it were possible to do the thing)",
      "And round a giant bathtub leave a mighty ring."
   ],
   "E1" : [
      "Figure E1: TYCOON (-1, -1, -1, -1)",
      "Descend we now into a deep crevasse",
      "To see, beneath the surface bleak and frore,",
      "The oxygen that made the chilly mass",
      "Into the ocean's ferrous ions pour",
      "Precipitating to the silty floor",
      "Layers that posterity will bringâ",
      "Upreared as mountains of rich IRON ORE:",
      "Then lodestone's magnet shall aberrent swing,",
      "Antipodean magnate strike the lyre and sing."
   ],
   "D27" : [
      "Figure D27: WATCHER (1, 0, -1, 1)",
      "Sobered, we leave that mournful place",
      "Southward to an adamantine cell",
      "A myriad of mirrors shows each face",
      "In sparkling facets, wonderful to tell.",
      "Here in this crystal, by atomic spell",
      "All that was thought or said, each laugh, each curse",
      "Is stored until the Universe's knell",
      "The story of your life, your dreams, this verse",
      "Until the very protons shimmer and disperse."
   ],
   "C14" : [
      "Figure C14: EINSTEIN (0, 0, 1, 1)",
      "All spinning like a jewelled orrery:",
      "But Mercury precessing, year to year,",
      "Abrogates NEWTON'S laws, and presently",
      "We see the clockwork cosmos decohere.",
      "Time slips, becoming relative: we fear",
      "The loss of rugged mechanism's clasp.",
      "But now we sense a burning hypersphere,",
      "Spinoza's geometric God: we gasp",
      "At fleeting visions that our minds can barely grasp."
   ],
   "B2" : [
      "Figure B2: SPINDRIFT (0, -1, 0, 0)",
      "In daylight, now, see breakers crash and hiss,",
      "They bring ambiguous gifts, long afloat:",
      "This fetid mass, the precious AMBERGRIS,",
      "Or refuse from the galley of a boat?",
      "An emerald, fit for a prince's throat,",
      "Or weathered fragment of a flask of ale?",
      "A totem, black and hornÃ©d like a goat,",
      "Or casing in which infant sharks set sail?",
      "Art and nature blend as mermaid's top and tail."
   ],
   "B8" : [
      "Figure B8: RECURSIVE (1, 0, 0, 0)",
      "On a resounding staircase we ascend",
      "To daylight and a spacious colonnade",
      "That faces hills, rolling without end",
      "To the horizon. Of marble made",
      "Dappled with patterns like to light and shade",
      "On forest floor, or ripples in a lake",
      "As if the same math'mathics were obeyed",
      "In rock, in branch, in flesh, in waves that break:",
      "All things with form from this their master-pattern take."
   ],
   "D29" : [
      "Figure D29: NILGIRI (1, 1, 0, -1)",
      "Eastward still, into a stony square",
      "Made of setts all in a honeycomb.",
      "Here, on a time, from its plutonic lair",
      "A great basaltic flood was let to roam,",
      "A fiery sea with pyroclastic foam",
      "Resistless in its terrible advance",
      "A continent aflame: but soon to loam",
      "Most fertile weathered down is the expanse.",
      "SHIVA, the Destroyer, blessed be thy dance."
   ],
   "B5" : [
      "Figure B5: GOLDEN (0, 0, 1, 0)",
      "A marble rooftop, open to the sky,",
      "Surrounded by eight towers, seen before:",
      "Mercury hot and cold, and Venus dry,",
      "Orthogonal Uranus, Neptune frore,",
      "Terra and Luna, on their temperate shore;",
      "The red of Mars and Jupiter's swirling dun, ",
      "Cold Saturn in his rings of glitt'ring hoar",
      "And myriads of planetesimals run",
      "All circling about their mighty mother SUN."
   ],
   "D30" : [
      "Figure D30: TINDER (1, 1, -1, 0)",
      "Down to a cellar, filled with a bracing air,",
      "Crisp, as when a child dashes a stone",
      "Down upon boulders and the sparks leap where",
      "Rock gnashes rock: here flints are shown",
      "Immur'd in lime, knobbed like shards of bone,",
      "Named PARAMOUDRA on Hibernia's shores,",
      "Fire's father, which was in ages grown",
      "In ancient seas. So Nature blindly stores",
      "Resources for mankind in humble madrepores."
   ],
   "C7" : [
      "Figure C7: EVENTIDE (0, -1, 0, -1)",
      "A dusky strand beneath a twilit wood",
      "Where no birds sing, heavy with moss and fern:",
      "In a warm age: never has forest stood",
      "So near the Pole, and, as the seasons turn",
      "The sun skims low and never dares to spurn",
      "The dark horizon. See, there, in the shade,",
      "A reptile's shape that heat will never burn,",
      "A great-eyed hunting lizard in the glade.",
      "Above, the Southern Lights in majesty arrayed."
   ],
   "D1" : [
      "Figure D1: GLACIAL (-1, -1, 0, -1)",
      "As we descend, with clouds of foggy breath",
      "We enter a bleak citadel of ice",
      "Facing a frozen plain. Nothing but death,",
      "It seems, rules here: see the heavy price",
      "Paid by the Earth, locked in a chilly vice.",
      "Yet it was tiny microbes made this pall",
      "(An age, yet in Earth's ages but a trice)",
      "Whose oxygen made greenhouse gases fall:",
      "Thus see a world transformed by the very small."
   ],
   "D4" : [
      "Figure D4: NEAT (-1, -1, 0, 1)",
      "Disgorged like Jonah from the living barque",
      "Wading through a foaming, busy sea",
      "We pass between great buttresses and dark,",
      "The members of a mighty BANYAN-TREE.",
      "Trained by genetick arts to remedy",
      "The planet's technological distress,",
      "Infusing its carbonic legacy",
      "Into the ocean, where it may harm less.",
      "See, the children play in waves that effervesce."
   ],
   "E10" : [
      "Figure E10: TRIPLE-ALPHA (1, -1, 1, -1)",
      "In the deep past, all was primal gas,",
      "The exhalation of the fading roar",
      "Of Universe's birth, but soon the mass",
      "Of the first uncouth stars made at their core",
      "A host of heavy atoms, and the spoor",
      "Of their explosive deaths made all the land",
      "And water, all of rich CREATION'S store.",
      "O, ye that wander, sift the ocean's sand:",
      "How many ancient stars are nestled in your hand?"
   ],
   "C3" : [
      "Figure C3: SULPHUR (-1, 0, -1, 0)",
      "Down a steep stair we fly the feath'ry stench",
      "In vain, for in the stony room below",
      "Wrung from the rock by stubborn nature's clench",
      "We see a vein of brimstone all aglow",
      "Its creeping azure flames can barely show",
      "Through the vile fumes, like unto an egg",
      "All rotted green inside its shell of snow",
      "Or as salt fish turned foul within its keg",
      "So to the northern door we turn an eager leg."
   ],
   "D12" : [
      "Figure D12: HUBBUB\r (-1, 1, 0, 1)",
      "Our hunger sated, northward, to a cage\r",
      "Of burnished copper. In the centre, see\r",
      "A speaking pillar: âYe of ancient age,\r",
      "âKnow that our science made telepathy,\r",
      "âLong a vain dream, an actuality\r",
      "âThat caught all living things in its embrace,\r",
      "âA global and unending colloquy.\r",
      "âAnd so we scattered from this noisy place,\r",
      "âSeeking refuge in the silences of SPACE.â\r"
   ],
   "C23" : [
      "Figure C23: ORBIT\r (1, 0, 0, 1)",
      "Descend from that high vision, dark and chill\r",
      "To Earth once more. The Sun, no more the bud\r",
      "Of blinding white we know, has bloomed until\r",
      "It covers half the sky. The ocean's flood\r",
      "Has boiled away: to brick has baked its mud.\r",
      "Mercury and Venus disappear\r",
      "Like iron pellets in a sea of blood.\r",
      "Yet see Man's metal servants whoop and cheer\r",
      "As Earth skips like a stone across the photosphere.\r"
   ],
   "E5" : [
      "Figure E5: SIDEROPHILE (-1, 1, -1, -1)",
      "A glowing spheroid, uniform and mixed,",
      "Was Earth when first from nebula congealed",
      "But soon it was in ordered layers fixed,",
      "For Chaos soon to Gravity must yield,",
      "And so, precipitate, the core was steeled,",
      "In its collapse provoking such a wave",
      "That throbbed the newly-formed magnetic field",
      "So great auroras ran from sky to cave",
      "Like to a rainbow, or the lasers at a RAVE."
   ],
   "C21" : [
      "Figure C21: IRON (1, 0, -1, 0)",
      "Flow back now, Time, and from the future long",
      "Return us to our era: walls and floor",
      "Of Iron now, corruptible and strong.",
      "IRON, of this our Earth the fiery core;",
      "IRON, gray as midnight, red with gore;",
      "IRON that ploughs the field and tames the wild;",
      "IRON, the soul of transport and of war;",
      "IRON, for which we feed th'indignant child",
      "Spinaches and liver, foodstuffs most revil'd."
   ],
   "D17" : [
      "Figure D17: ASH (0, 1, -1, -1)",
      "From that ill chamber, in the solar track--",
      "But still below, where never sun has shone--",
      "And still in ancient time, we find a black",
      "And cindered remnant of a world long gone,",
      "HADEAN Earth, when fire danced upon",
      "A sea of molten rock; when creatures dire",
      "Disported in the lava. Pale and wan",
      "To them would seem our world of buried fire,",
      "The cooling of the crust to them a a funeral pyre."
   ],
   "E16" : [
      "Figure E16: ACCRETION\r (1, 1, 1, 1)",
      "Ascend: to see the monster at the heart,\r",
      "Devourer of suns, a DARKLING STAR.\r",
      "Although it seem that it must be the part\r",
      "Of every mass to fall into this scar\r",
      "Upon the void, geometry shall bar\r",
      "Its passage, as the needle's narrow eye\r",
      "Will scarce admit the camel. It is far\r",
      "More straitened, a pinpoint against a sky.\r",
      "So, crowding at the gate, the fierce emissions sigh.\r"
   ]
}
;

var rooms = {
   "E15" : [
      1,
      1,
      -1,
      1
   ],
   "E13" : [
      1,
      1,
      -1,
      -1
   ],
   "B6" : [
      0,
      0,
      0,
      1
   ],
   "E8" : [
      -1,
      1,
      1,
      1
   ],
   "C18" : [
      0,
      1,
      0,
      1
   ],
   "C11" : [
      0,
      0,
      -1,
      -1
   ],
   "C1" : [
      -1,
      -1,
      0,
      0
   ],
   "D13" : [
      0,
      -1,
      -1,
      -1
   ],
   "E9" : [
      1,
      -1,
      -1,
      -1
   ],
   "C8" : [
      0,
      -1,
      -1,
      0
   ],
   "D24" : [
      1,
      -1,
      0,
      1
   ],
   "C2" : [
      -1,
      0,
      0,
      -1
   ],
   "D18" : [
      0,
      1,
      1,
      -1
   ],
   "D21" : [
      1,
      -1,
      0,
      -1
   ],
   "E7" : [
      -1,
      1,
      -1,
      1
   ],
   "B1" : [
      -1,
      0,
      0,
      0
   ],
   "E6" : [
      -1,
      1,
      1,
      -1
   ],
   "C17" : [
      0,
      1,
      1,
      0
   ],
   "E2" : [
      -1,
      -1,
      1,
      -1
   ],
   "D6" : [
      -1,
      0,
      1,
      -1
   ],
   "D15" : [
      0,
      -1,
      -1,
      1
   ],
   "C12" : [
      0,
      0,
      1,
      -1
   ],
   "D26" : [
      1,
      0,
      1,
      -1
   ],
   "D20" : [
      0,
      1,
      1,
      1
   ],
   "C19" : [
      1,
      -1,
      0,
      0
   ],
   "E14" : [
      1,
      1,
      1,
      -1
   ],
   "D14" : [
      0,
      -1,
      1,
      -1
   ],
   "D8" : [
      -1,
      0,
      1,
      1
   ],
   "E3" : [
      -1,
      -1,
      -1,
      1
   ],
   "D11" : [
      -1,
      1,
      1,
      0
   ],
   "D19" : [
      0,
      1,
      -1,
      1
   ],
   "D22" : [
      1,
      -1,
      -1,
      0
   ],
   "B7" : [
      0,
      1,
      0,
      0
   ],
   "D7" : [
      -1,
      0,
      -1,
      1
   ],
   "D32" : [
      1,
      1,
      0,
      1
   ],
   "B3" : [
      0,
      0,
      0,
      -1
   ],
   "C15" : [
      0,
      1,
      0,
      -1
   ],
   "D10" : [
      -1,
      1,
      -1,
      0
   ],
   "A1" : [
      0,
      0,
      0,
      0
   ],
   "B4" : [
      0,
      0,
      -1,
      0
   ],
   "D25" : [
      1,
      0,
      -1,
      -1
   ],
   "D28" : [
      1,
      0,
      1,
      1
   ],
   "D16" : [
      0,
      -1,
      1,
      1
   ],
   "D5" : [
      -1,
      0,
      -1,
      -1
   ],
   "D31" : [
      1,
      1,
      1,
      0
   ],
   "E11" : [
      1,
      -1,
      -1,
      1
   ],
   "E4" : [
      -1,
      -1,
      1,
      1
   ],
   "C16" : [
      0,
      1,
      -1,
      0
   ],
   "C6" : [
      -1,
      1,
      0,
      0
   ],
   "C5" : [
      -1,
      0,
      0,
      1
   ],
   "D9" : [
      -1,
      1,
      0,
      -1
   ],
   "C24" : [
      1,
      1,
      0,
      0
   ],
   "C4" : [
      -1,
      0,
      1,
      0
   ],
   "C13" : [
      0,
      0,
      -1,
      1
   ],
   "C10" : [
      0,
      -1,
      0,
      1
   ],
   "D23" : [
      1,
      -1,
      1,
      0
   ],
   "C20" : [
      1,
      0,
      0,
      -1
   ],
   "C22" : [
      1,
      0,
      1,
      0
   ],
   "C9" : [
      0,
      -1,
      1,
      0
   ],
   "D2" : [
      -1,
      -1,
      -1,
      0
   ],
   "E12" : [
      1,
      -1,
      1,
      1
   ],
   "D3" : [
      -1,
      -1,
      1,
      0
   ],
   "E1" : [
      -1,
      -1,
      -1,
      -1
   ],
   "C14" : [
      0,
      0,
      1,
      1
   ],
   "D27" : [
      1,
      0,
      -1,
      1
   ],
   "B2" : [
      0,
      -1,
      0,
      0
   ],
   "B8" : [
      1,
      0,
      0,
      0
   ],
   "D29" : [
      1,
      1,
      0,
      -1
   ],
   "B5" : [
      0,
      0,
      1,
      0
   ],
   "D30" : [
      1,
      1,
      -1,
      0
   ],
   "C7" : [
      0,
      -1,
      0,
      -1
   ],
   "D1" : [
      -1,
      -1,
      0,
      -1
   ],
   "D4" : [
      -1,
      -1,
      0,
      1
   ],
   "E10" : [
      1,
      -1,
      1,
      -1
   ],
   "D12" : [
      -1,
      1,
      0,
      1
   ],
   "C3" : [
      -1,
      0,
      -1,
      0
   ],
   "C23" : [
      1,
      0,
      0,
      1
   ],
   "E5" : [
      -1,
      1,
      -1,
      -1
   ],
   "C21" : [
      1,
      0,
      -1,
      0
   ],
   "D17" : [
      0,
      1,
      -1,
      -1
   ],
   "E16" : [
      1,
      1,
      1,
      1
   ]
}
;

